# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: 'npm install && npm audit fix'
      - run:
          name: Configuring permissions
          command: sudo chown -R $USER /usr/local/lib/node_modules
      - run:
          name: Install solcjs
          command: npm install -g solc
      - run:
          name: Compile Solidity Contracts
          command: solcjs --bin --abi --include-path node_modules/ --base-path . -o build/ contracts/*.sol
      - run:
          name: Generate a Java Wrapper
          command: web3j solidity generate -b MyNFT.bin -a MyNFT.abi -o src/main/java -p com.example
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build