# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.9.0-browsers

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install web3js web3j solc-js solc
          command: npm install web3js web3j solc-js solc
      - run:
          name: Audit Dependencies
          command: npm audit fix || true
      - run:
          name: Compile Solidity Contracts
          command: solcjs --bin --abi --include-path node_modules/ --base-path . -o build/ contracts/*.sol || true
      - run:
          name: Generate a Java Wrapper
          command: web3j solidity generate -b MyNFT.bin -a MyNFT.abi -o src/main/java -p com.example || true
      - run:
          name: Run Tests
          command: npm test || true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build